### ISSUE TITLE
Error: Member not found: 'MediaQuery.sizeOf'

### ISSUE THREAD

**Issue by Anquuni** [Jamalianpour/easy_sidemenu#62]
I added easy_sidemenu to my `pubspec.yaml`
```
environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.0

  provider: ^4.3.3
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  google_sign_in: ^6.1.4
  firebase_database: ^10.2.4
  scrollable_positioned_list: ^0.3.8
  easy_sidemenu: ^0.5.0
```

and only imported the package in one of my pages (I did not use it yet)
```
import 'package:easy_sidemenu/easy_sidemenu.dart';
```

I did run `flutter pub get` and started my application which results in the following error:
```
../../../AppData/Local/Pub/Cache/hosted/pub.dev/easy_sidemenu-0.5.0/lib/src/side_menu.dart:106:22: Error: Member not found: 'MediaQuery.sizeOf'.
      if (MediaQuery.sizeOf(context).width > collapseWidth &&
                     ^^^^^^
```

I was only able to fix the error by downgrading to version `^0.4.2`
